name: thikthp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter_form_builder: ^9.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  toast: ^0.3.0
  provider: ^6.1.1
  flutter_pdfview: ^1.2.7
  image_picker: ^1.0.5
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/pdf/
    - assets/music/
  fonts:
    - family: PacificoRegular
      fonts:
        - asset: assets/font/PacificoRegular.ttf
    - family: QwigleyRegular
      fonts:
        - asset: assets/font/QwigleyRegular.ttf
